### ISSUE TITLE
有关webpack的重复打包问题以及使用JQ插件的问题想请教一下

### ISSUE THREAD

**Issue by laixstx** [vhtml/webpack-MultiPage-static#1]
文章写得挺赞的！不过个人有几个问题想请教一下：
1、我现在是用webpack搭建多页面的web项目，项目有n多个页面，而每次运行webpack进行打包之后，webpack都会将所有的文件都重新打包一次，这样的话很浪费资源而且不太合理...
比如，我现在有login.html,userList.html,adminList.html三个页面，每个页面都有一个对应的入口文件（login.js,userList.js,adminList.js），假设开发项目的周期是一个月，如果我今天只是开发了login相关的功能，然后明天我要接着开发userList相关的功能，那么当我运行 webpack 命令之后，之前没有修改过而且不需要修改的login相关的js/css等文件又被毫无意义地重新打包了一次，这样的话，随着项目周期越来越长，页面越来越多，而每当我运行 webpack 命令，那些之前早就开发好的功能都要被无意义地重新打包一次吗？？我只是想将我当天的开发功能和作了修改的功能重新打包就好了，之前已经开发好的功能我肯定是不想再重新又打包生成一次了。而且，在生产环境中，每次打包生成的文件都加了hash，那么旧的文件改怎么处理呢？总不能每次重新打包都先将所有旧的文件都清理一遍吧？
不知道我能不能把问题给说清楚，就想请教一下，这个问题您是怎么处理的呢？

2、结合webpack该怎么使用jquery的插件呢？比如在login的功能中使用 sweetalert 插件（它有 sweetalert.css/sweetalert.min.css和sweetalert.js/sweetalert.min.js这些文件），我是用npm下载sweetalert的。现在我在login.js入口文件中import "sweetalert/dist/sweetalert.css"，然后在需要使用sweetalert的组件LoginForm.js中import sweetalert from 'sweetalert'; 
可是webpack会报错：

> ERROR in ./~/sweetalert/dist/sweetalert.css
> Module parse failed: F:\MyFiles\myPro\watermirrorPro\shv\view\node_modules\sweetalert\dist\swee
> talert.css Unexpected token (1:20)
> You may need an appropriate loader to handle this file type.
> SyntaxError: Unexpected token (1:20)

我在webpack的配置文件中已经做了配置，也已经安装了相应的loader，我 import 其他的 css 文件是没有问题的，只是import "sweetalert/dist/sweetalert.css"这个的时候却报错了。。。这是怎么回事呢？麻烦大神帮忙解答一下

**Comment by vhtml** [comment]
我先来回来第二个问题吧，如果你在打包时开启了devtool，建议关闭掉试试，如果关闭掉打包没有问题的话，那这个就是babel的一个一直未fix的bug了。

第一个问题，每次打包前都是需要将之前打包好的先删除清理掉，这个可以借鉴下vue-cli的配置。由于每次打包为确保相关页面commonChunks一致以及为变动部分加上hash，这些是必做的工作，而且频率又不频繁，只在上线时打包一次，所花费的时间又不长，比起java每次看效果都要编译一次不知道方便多少。

其次旧的打包文件完全可以不必清理，放在那也是没有关系的，如果你不是处女座的话。
