### ISSUE TITLE
new HtmlWebpackPlugin（）没个页面都要配置 ？

### ISSUE THREAD

**Issue by IdenPin** [vhtml/webpack-MultiPage-static#3]
//HtmlWebpackPlugin，模板生成相关的配置，每个对于一个页面的配置，有几个写几个。这块有更好的解决方案么 ？项目实战中会有很多页面，都要这样一一配置么 。

**Comment by vhtml** [comment]
确实是这样，你可以参考下一篇[基于webpack的前端工程化开发之多页站点篇（二）](https://github.com/vhtml/webpack-MultiplePage)
